'use strict';

var userAddress = null;
var pubKey      = null;
var walletType  = null;
var walletPrefersAmino = false;
var keystoneSdk = null;
var keystoneViewSdk = null;
var keystoneAccount = null;
var keystoneBootstrapped = false;
var ledgerApp   = null;
var ledgerTransport = null;
var selectedTld = null;
var selectedTldPolicy = null;
var currentManagedDomain = null;
var editingTld = null;
var tldPendingLabel = null;
var tldPendingSecret = null;
var tldCommitTimestamp = null;
var tldTimerInterval = null;
var allTlds = [];
