[package]
name = "atom-names-registrar"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw2.workspace = true
thiserror.workspace = true
atom-names-types.workspace = true
atom-names-utils.workspace = true
